import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                surface: '#f8f9ff',
                'surface-dim': '#cbdbf5',
                'surface-bright': '#f8f9ff',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#eff4ff',
                'surface-container': '#e5eeff',
                'surface-container-high': '#dce9ff',
                'surface-container-highest': '#d3e4fe',
                'on-surface': '#0b1c30',
                'on-surface-variant': '#5c4037',
                'inverse-surface': '#213145',
                'inverse-on-surface': '#eaf1ff',
                outline: '#907065',
                'outline-variant': '#e5beb2',
                'surface-tint': '#ac3500',
                primary: '#a83300',
                'on-primary': '#ffffff',
                'primary-container': '#d24200',
                'on-primary-container': '#fffbff',
                'inverse-primary': '#ffb59d',
                secondary: '#5d5e61',
                'on-secondary': '#ffffff',
                'secondary-container': '#e2e2e5',
                'on-secondary-container': '#636467',
                tertiary: '#894d00',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#ac6300',
                'on-tertiary-container': '#fffbff',
                error: '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'primary-fixed': '#ffdbd0',
                'primary-fixed-dim': '#ffb59d',
                'on-primary-fixed': '#390c00',
                'on-primary-fixed-variant': '#832600',
                'secondary-fixed': '#e2e2e5',
                'secondary-fixed-dim': '#c6c6c9',
                'on-secondary-fixed': '#1a1c1e',
                'on-secondary-fixed-variant': '#454749',
                'tertiary-fixed': '#ffdcbf',
                'tertiary-fixed-dim': '#ffb874',
                'on-tertiary-fixed': '#2d1600',
                'on-tertiary-fixed-variant': '#6a3b00',
                background: '#f8f9ff',
                'on-background': '#0b1c30',
                'surface-variant': '#d3e4fe',
            },
            fontFamily: {
                heading: ['"Plus Jakarta Sans"', ...defaultTheme.fontFamily.sans],
                body: ['"Work Sans"', ...defaultTheme.fontFamily.sans],
                sans: ['"Work Sans"', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                h1: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
                h2: ['36px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
                h3: ['24px', { lineHeight: '1.3', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
                'body-sm': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
                'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
            },
            borderRadius: {
                sm: '0.25rem',
                DEFAULT: '0.5rem',
                md: '0.75rem',
                lg: '1rem',
                xl: '1.5rem',
            },
            spacing: {
                gutter: '24px',
                margin: '32px',
            },
            maxWidth: {
                app: '1200px',
            },
            boxShadow: {
                card: '0px 4px 20px rgba(0, 0, 0, 0.05)',
                overlay: '0px 8px 32px rgba(11, 28, 48, 0.12)',
            },
        },
    },

    plugins: [forms],
};
